from enum import StrEnum


class AuditEventType(StrEnum):
    API_KEY_CREATED = "API_KEY_CREATED"
    API_KEY_REVOKED = "API_KEY_REVOKED"
    API_KEY_UPDATED = "API_KEY_UPDATED"
    COMMENT_ADDED = "COMMENT_ADDED"
    COMMENT_DELETED = "COMMENT_DELETED"
    COMMENT_EDITED = "COMMENT_EDITED"
    ITEM_APPROVED = "ITEM_APPROVED"
    ITEM_CHANGE_REQUESTED = "ITEM_CHANGE_REQUESTED"
    ITEM_CREATED = "ITEM_CREATED"
    ITEM_DELETED = "ITEM_DELETED"
    ITEM_REJECTED = "ITEM_REJECTED"
    ITEM_VERSION_CREATED = "ITEM_VERSION_CREATED"
    MEMBERSHIP_CHANGED = "MEMBERSHIP_CHANGED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_DELETED = "PROJECT_DELETED"
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"
    PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED"
    PROJECT_MEMBER_ROLE_CHANGED = "PROJECT_MEMBER_ROLE_CHANGED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    USER_DELETED = "USER_DELETED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    WEBHOOK_CREATED = "WEBHOOK_CREATED"
    WEBHOOK_DELETED = "WEBHOOK_DELETED"
    WEBHOOK_UPDATED = "WEBHOOK_UPDATED"

    def __str__(self) -> str:
        return str(self.value)
